#!/bin/bash
file_path=$(dirname $(realpath $0))
plugin_dir=$file_path/plugins
plugin_dir2=$HOME/.oh-my-zsh/plugins

export ZSH_CUSTOM=$file_path
export PATH=$HOME/.local/bin:$HOME/Programs:$PATH
export EDITOR="nvim -u ${HOME}/.vimrc"

plugins=(zsh-vi-mode)

for plugin in "${plugins[@]}"
do
        if [[ -d "$plugin_dir/$plugin" ]]
        then
            source $plugin_dir/$plugin/$plugin.plugin.zsh

        elif [[ -d "$plugin_dir2/$plugin" ]]
        then
            source $plugin_dir2/$plugin/$plugin.plugin.zsh

        fi
done

alias vim="nvim -u $HOME/.vimrc"
#alias sleep="echo mem | sudo tee /sys/power/state"
export EDITOR=nvim
ZVM_VI_INSERT_ESCAPE_BINDKEY=jj

#For systemd services
echo "DBUS_SESSION_BUS_ADDRESS=$(echo $DBUS_SESSION_BUS_ADDRESS | cut -d "," -f 1)" > $HOME/.my_env
